### ISSUE TITLE
[POST] Markdown Parsing

### ISSUE THREAD

**Issue by henrystoll** [LukaHarambasic/recommend.tools#22]
- [x] TOC
- [ ] image styling
- [ ] `code` styling
- [ ] automatic link creation when using # or \ in md article
- [ ] Table Styling
- [ ] Footnote support

**Comment by LukaHarambasic** [comment]
the TOC is still working, but your gdoc to markdown parser did everything right. So we only have h2 up to h4 headlines, the TOC only will work for h1 headlines.

**Comment by LukaHarambasic** [comment]
And please create one issue per feature otherwise we could use just a list.
